# Generated by Django 4.2.4 on 2023-08-16 06:51

import django.core.validators
from django.db import migrations, models
import eventer_app.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(max_length=20, validators=[eventer_app.profiles.validators.validate_password_contains_digit, django.core.validators.MinLengthValidator(5)]),
        ),
    ]
